const x = "10";

try {
    x = 5;
} catch (error) {
    console.log(`Erro: ${error}`);
}